language: python
python: "3.6"
cache:
  pip: true

# Use container-based infrastructure
dist: trusty
sudo: false

install:
  - pip install wheel
  - pip install -e .[testing]

script:
  - flake8 wagtailrelated
  - isort --check-only --diff --recursive wagtailrelated
